# Generated by Django 6.0 on 2026-02-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="message",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="receiver",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room_name",
            field=models.CharField(default="general", max_length=255),
            preserve_default=False,
        ),
    ]
