# Generated by Django 6.0 on 2026-02-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_chatmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="title",
            field=models.CharField(blank=True, default="Instructor", max_length=100),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("dropped", "Dropped"),
                    ("blocked", "Blocked"),
                ],
                default="ongoing",
                max_length=20,
            ),
        ),
    ]
