# Generated by Django 6.0 on 2026-02-10 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_teacherprofile_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statusupdate",
            name="student",
        ),
        migrations.AddField(
            model_name="statusupdate",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
