# Generated by Django 6.0 on 2026-02-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_statusupdate_student_statusupdate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusupdate",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="status_uploads/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gpa",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="title",
            field=models.CharField(blank=True, default="Lecturer", max_length=100),
        ),
    ]
