# Generated by Django 6.0 on 2026-02-16 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_statusupdate_file_studentprofile_gpa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusupdate",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_updates",
                to="core.course",
            ),
        ),
        migrations.AddField(
            model_name="statusupdate",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
