# Generated by Django 6.0 on 2026-02-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadline",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="deadlines/"),
        ),
    ]
