# Generated by Django 6.0 on 2026-02-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_deadline_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_code",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
    ]
