# Generated by Django 6.0 on 2026-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_course_course_code_remove_course_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
