# Generated by Django 6.0 on 2026-02-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_course_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
